CS2103-AY1819S1-F11-3/main

- docs/DeveloperGuide.adoc
Updated user stories, use cases, value proposition, glossary, misc
> [v1.1] DeveloperGuide: Update DeveloperGuide for 1.1

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/model/person/Status.java
- src/main/java/seedu/address/model/person/Task.java
- src/main/java/seedu/address/storage/XmlAdaptedTask.java
- src/main/java/seedu/address/ui/TaskCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/data/XmlSerializableTaskManagerTest/duplicateTaskTaskManager.xml
- src/test/data/XmlSerializableTaskManagerTest/invalidTaskManager.xml
- src/test/data/XmlSerializableTaskManagerTest/typicalTasksTaskManager.xml
- src/test/data/XmlTaskManagerStorageTest/invalidAndValidTaskTaskManager.xml
- src/test/data/XmlTaskManagerStorageTest/invalidTaskManager.xml
- src/test/data/XmlUtilTest/invalidTaskField.xml
- src/test/data/XmlUtilTest/missingTaskField.xml
- src/test/data/XmlUtilTest/validTask.xml
- src/test/data/XmlUtilTest/validTaskManager.xml
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/model/person/StatusTest.java
- src/test/java/seedu/address/testutil/EditTaskDescriptorBuilder.java
- src/test/java/seedu/address/testutil/TaskBuilder.java
- src/test/java/seedu/address/testutil/TypicalTasks.java
- src/test/java/seedu/address/ui/TaskListPanelTest.java
- src/test/java/systemtests/EditCommandSystemTest.java
Change Log
---
* Add new field Status to Task. A Task can have three possible status: IN_PROGRESS, FINISHED and OVERDUE.
* Status.IN_PROGRESS has value "IN PROGRESS", Status.FINISHED has value "FINISHED", Status.OVERDUE has value "OVERDUE". These values are mainly for display to the user.
* New Tasks are automatically assigned the Status of IN_PROGRESS.
* Modified EditCommand and related classes to enable editing of status. Status should be updated from IN_PROGRESS to FINISHED and vice versa through a separate command. This can be done by calling the executeEditStatus static method of EditCommand. The method signature is as follows:
`public static CommandResult executeEditStatus (Index index, Status status, Model model, CommandHistory history)`
Example: 
```
Class ExampleCommand {
private …
```
> Add Status field

- src/main/java/seedu/address/model/person/DueDate.java
- src/main/java/seedu/address/model/util/DateFormatUtil.java
- added a class to format dateparsing
src/main/java/seedu/address/model/util/DateFormatUtil.java
- removed excess functions from DueDate
src/main/java/seedu/address/model/person/DueDate.java
> Add DateFormatUtil class

- build.gradle
Change log
---
update site-wide documentation setting in gradle.build according to developer guide section 4.4. Site-wide Documentation Settings
> Update site-wide doc settings

- docs/UserGuide.adoc
Change Log
---
modify UserGuide to include only currently implemented commands
> Update UserGuide for v1.1

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/person/PriorityValue.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/test/data/XmlSerializableTaskManagerTest/duplicateTaskTaskManager.xml
- src/test/data/XmlSerializableTaskManagerTest/typicalTasksTaskManager.xml
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditTaskDescriptorTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/TaskManagerTest.java
- src/test/java/seedu/address/model/person/TaskTest.java
- src/test/java/seedu/address/model/person/UniqueTaskListTest.java
- src/test/java/seedu/address/testutil/TypicalTasks.java
- src/test/java/systemtests/AddCommandSystemTest.java
- src/test/java/systemtests/EditCommandSystemTest.java
Changelog:
- No change to regex for validity: Description must be nonempty, but is otherwise unrestricted. 
- Renamed method names, field names, string values and xml values.
Additional:
- Fix some lingering PriorityValue changes
> Description field

- src/test/java/seedu/address/model/person/UniqueTaskListTest.java
Changelog:
- A few lingering instances of UniquePersonList changed
> Refactor UniqueTaskList

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/model/task/Status.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/model/task/StatusTest.java
Change Log
---
* Modify names of StatusTest methods
* Remove unused executeEditStatus method in  EditCommand
* Simple string refactoring in EditCommand and EditCommandTest
> Modify status test name and simple refactoring

- .github/ISSUE_TEMPLATE/custom-project-task-template.md
- .github/ISSUE_TEMPLATE/issue-story-template.md
Add new issue template for project tasks. (since we need to use issues to track and assign tasks)
> Update issue templates

- README.adoc
> Add Coveralls for Repo

- README.adoc
Did not properly update the link in #90
> Add coveralls again

- docs/UserGuide.adoc
> Update User Guide for Complete Command

- src/main/java/seedu/address/logic/commands/DependencyCommand.java
- src/main/java/seedu/address/model/DependencyGraph.java
- src/main/java/seedu/address/model/task/exceptions/GraphCycleException.java
- src/test/java/seedu/address/logic/commands/DependencyCommandTest.java
- src/test/java/seedu/address/logic/parser/ParserUtilTest.java
- src/test/java/seedu/address/model/task/DependencyGraphTest.java
- src/test/java/seedu/address/testutil/TaskBuilder.java
Resolves #85 
1) Added functionality to check dependency cycles among tasks.
Refer to `src/main/java/seedu/address/model/DependencyGraph.java` for details on usage.
2) DependencyCommand now checks for dependency cycle before adding dependency, else error is thrown.
3) Topological sort can be performed to display tasks sorted topologically. Function is to be used in list or in aiding the display of appropriate tasks. (@remo5000: for reference)
src/main/java/seedu/address/model/DependencyGraph.java
src/test/java/seedu/address/model/task/DependencyGraphTest.java
src/main/java/seedu/address/logic/commands/DependencyCommand.java
src/main/java/seedu/address/model/task/exceptions/GraphCycleException.java
src/test/java/seedu/address/logic/commands/DependencyCommandTest.java …
> Dependency validity

- src/main/java/seedu/address/logic/commands/CompleteCommand.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/TaskManager.java
- src/main/java/seedu/address/model/achievement/Level.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
Works towards #109 
src/main/java/seedu/address/logic/commands/CompleteCommand.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/TaskManager.java
src/main/java/seedu/address/model/achievement/Level.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
Creates #143
> Enhance CompleteCommand: Add reporting feature on level up

- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/parser/ListCommandParser.java
- src/main/java/seedu/address/model/task/DueDateIsBeforeEndOfMonthPredicate.java
- src/main/java/seedu/address/model/task/DueDateIsBeforeEndOfWeekPredicate.java
- src/test/java/seedu/address/logic/commands/ListCommandTest.java
- src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
- Added end of month and end of week filters for ListCommand
- Added tests for ListCommandParser
- Added test for the ListCommands with the new parameters
> ListCommand: Add filters for end of week/month

- src/main/java/seedu/address/model/task/LabelMatchesKeywordPredicate.java
- src/test/java/seedu/address/model/task/LabelMatchesKeywordPredicateTest.java
Fixes #152 with test cases to verify correctness
> Complete label command case insensitive match

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- src/main/java/seedu/address/model/task/UniqueTaskList.java
This PR will delete dependencies on task to be deleted.
> Delete dependencies on task deletion

- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/commands/Command.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
Edit command previously did not edit status if due date is changed. Resolves #187.
> Fix edit command 

- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/commands/ShowTopologicalOrderCommand.java
- src/main/java/seedu/address/logic/parser/TaskManagerParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/ReadOnlyTaskManager.java
- src/main/java/seedu/address/model/TaskManager.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/model/TaskManagerTest.java
Command lists the topological order of all uncompleted tasks. 
Files modified:
docs/UserGuide.adoc
src/main/java/seedu/address/logic/parser/TaskManagerParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/ReadOnlyTaskManager.java
src/main/java/seedu/address/model/TaskManager.java
Files added:
src/main/java/seedu/address/logic/commands/ShowTopologicalOrderCommand.java
> List topological order command

- src/test/java/seedu/address/logic/commands/AchievementsCommandTest.java
- src/test/java/seedu/address/logic/parser/AchievementsCommandParserTest.java
Change Log
---
Resolved #99 
Add tests for achievements command and parser.
> Add achievements command and parser test

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- docs/team/unsatisfiedpopcorn.adoc
> Add First Draft for PPP Jeff

- src/main/java/seedu/address/logic/commands/Command.java
- src/main/java/seedu/address/logic/commands/ShowTopologicalOrderCommand.java
- src/main/java/seedu/address/model/task/DueDate.java
- src/main/java/seedu/address/model/task/Task.java
- src/main/java/seedu/address/ui/StatusBarFooter.java
- src/main/java/seedu/address/ui/TaskCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/java/guitests/guihandles/TaskCardHandle.java
Add UI, functions support to display time until Task is due. 
Resolves #98
**Files changed:**
src/main/java/seedu/address/logic/commands/Command.java
src/main/java/seedu/address/model/task/DueDate.java
src/main/java/seedu/address/model/task/Task.java
src/main/java/seedu/address/ui/StatusBarFooter.java
src/main/java/seedu/address/ui/TaskCard.java
src/main/resources/view/PersonListCard.fxml
src/test/java/guitests/guihandles/TaskCardHandle.java
> Add functionalities to display time until due date

- docs/team/unsatisfiedpopcorn.adoc
> Add link to code contributed for PPP

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- docs/team/jiaxiu11.adoc
- src/main/java/seedu/address/logic/commands/AchievementsCommand.java
Change log
---
* add ppp
* fix ach command messages
> Add ppp for Jiaxiu

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- docs/team/pengnam.adoc
- src/main/java/seedu/address/model/DependencyGraph.java
- src/main/java/seedu/address/model/task/Task.java
1) Add PPP
2) Refactor code, add defensive checks, improve code quality
--> Handle TODOs
> Add PPP and refactor code for submission

- docs/UserGuide.adoc
- src/main/java/seedu/address/logic/commands/ModeCommand.java
- src/main/java/seedu/address/logic/parser/ModeCommandParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/TaskManager.java
- src/main/java/seedu/address/model/game/FlatMode.java
- src/main/java/seedu/address/model/game/GameManager.java
- src/main/java/seedu/address/model/game/IncreasingMode.java
- src/main/java/seedu/address/model/game/PriorityMode.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- Add two new modes: Increasing and Priority
- Add game difficulty
> Edit mode command

- docs/UserGuide.adoc
- src/main/java/seedu/address/model/game/GameManager.java
- src/main/java/seedu/address/model/game/PriorityMode.java
Allow priority mode to react to difficult level rather than remaining constant.
> Extend priority mode

- src/main/java/seedu/address/logic/commands/ClearCommand.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/test/java/seedu/address/logic/commands/AddCommandTest.java
- src/test/java/seedu/address/logic/commands/ClearCommandTest.java
- src/test/java/systemtests/ClearCommandSystemTest.java
> Prevent achievement info from getting reset on clear command

- src/main/java/seedu/address/model/task/DueDate.java
- src/main/java/seedu/address/ui/TaskCard.java
- src/main/java/seedu/address/ui/TaskViewPanel.java
1) Added a static function that truncates the label name
2) Used this function in TaskCard and TaskViewPanel
> Truncate Task labels

- docs/UserGuide.adoc
- docs/team/remo5000.adoc
> Vignesh PPP: Add minor feature

- docs/DeveloperGuide.adoc
- docs/UserGuide.adoc
- docs/team/remo5000.adoc
- Added manual test for list filters
- Added manual test for task view panel
- Added note for editable fields docs
- Added dependencies to editable fields docs
> Add Manual Testing section for ListCommand filters and TaskViewPanel UI

- docs/DeveloperGuide.adoc
- docs/team/remo5000.adoc
- Add Target User Profile
- Update Vignesh PPP Title
> Add Target User Profile
